import { NextPage } from "next";
import Head from "next/head";
import Sidebar from "@/components/layout/Sidebar";
import Navbar from "@/components/layout/Navbar";
import Header from "@/components/layout/Header";
import Cta from "@/components/layout/Cta";
import Achivment from "@/components/layout/achivment";
import Gallery from "@/components/layout/Gallery";
import About from "@/components/layout/About";
import Lokasi from "@/components/layout/Lokasi";
import FloatingWhatsApp from "@/components/FloatingWhatsApp";
import Footer from "@/components/layout/Footer";


const Index: NextPage = () => {
  return (
    <>
      <Head>
        <title>TahuPakBGMagelang</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
       <Navbar />
      <Sidebar />
      <About/>
      <Header />
      <Cta/>
      <Gallery />
      <Lokasi/>
      <FloatingWhatsApp />
      <Footer/>

    
    </>
  );
};

export default Index;
